name = "UomDefinitions"
uuid = "5c4bf7a8-0757-40b8-9968-47d0ead680d5"
authors = ["Jose Guzman <pepetavo@pm.me>"]
version = "0.1.0"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"

[compat]
ConstructionBase = "1.6.0"
